### ISSUE TITLE
Rich Text Doesn't Work as Described in the Documentation

### ISSUE THREAD

**Issue by saukif** [jobsta/reportbro-designer#127]
When adding HTML tags in the Rich Text editor, the tags are displayed as plain text in the preview instead of being rendered. This behavior is inconsistent with expected functionality.
![image](https://github.com/user-attachments/assets/870b6ff1-0946-45fa-8fd1-c643416ba097)

**Comment by mariarauch** [comment]
You can pass HTML tags to the richtext editor as parameters of type richtext, see parameter documentation: section https://www.reportbro.com/doc/userguide#parameter_type_rich_text
<img width="385" alt="Screenshot 2024-12-03 at 10 19 44" src="https://github.com/user-attachments/assets/af790009-e06a-4941-87e8-c1c9db16c454">

Instead of HTML input into the richtext editor you would use rich text formatting directly.
