### ISSUE TITLE
delete parameter programmatically

### ISSUE THREAD

**Issue by alfupe** [jobsta/reportbro-designer#22]
Hi there,

Is there any way to delete a previously added parameter? I have leveraged `reportbro.createParameter(parameterData)` previously and works perfectly nevertheless `reportbro.deleteParameter(parameter)` not.

For instance, this do nothing.
```javascript
const parameterName = 'page_total';
const parameter = reportBro.getParameterByName(parameterName);
reportBro.deleteParameter(parameter);
```

Is there a way to do that? Thanks!

**Comment by alhman** [comment]
these functions like deleteParameter are not meant for public use. You should only use the officially documented methods:
https://www.reportbro.com/docs/methods
in the code these are the methods after the
// API functions
comment.

deleteParameter only deletes the internal parameter data object. To delete the parameter from the gui you also have to delete the panel item for the parameter:
`parameter.getPanelItem().getParent().removeChild(parameter.getPanelItem());`

but I would not recommend to use any non public methods because they could change in a future release.

Why are you manually deleting a parameter? If we understand your use case, we'll think about adding official API methods in the next release.

**Comment by alfupe** [comment]
@alhman wow! that worked perfectly. Thanks a lot!

The application in which we are working to implement reportBro has the special need to have a 1:1 relation between some docElements and some parameters. I have to be able to:  
- create docElements and their related parameters programmatically and
- delete a related parameter when deleting a docElement...

Since the some parameters a tightly tied to some docElements, if we do not delete them we would get this error when printing due to parameter duplication:
![image](https://user-images.githubusercontent.com/6408433/59554278-081aee00-8fa1-11e9-8f55-8ccaba07325c.png)

It is very likely that people willing to use reportBro would need more methods to create doc elements, to delete them, to access to your wonderful method `getUniqueId` instead of having to control the id value when creating elements, and so on. In summary, it would be amazing if you open the API making it more developer friendly.

Said that, reportBro is a masterpiece. Thanks for that.
