### ISSUE TITLE
Portuguese characters not working...

### ISSUE THREAD

**Issue by ramstein74** [jobsta/reportbro-designer#35]
Hello this code does not work because of portuguese chars

report = Report(definition,     {
       "TITLE":"Certificado de Análise"
}

Análise has a "á" that replaced with just "a" works perfectly but in portugal we need this special characters.

what shoud i do ??

Regards
António

**Comment by alhman** [comment]
your description is very confusing. where does the data come from? as you can test in the live demos there is no problem using Portuguese characters in text. You only have to be careful when using non-latin1 characters to make sure the font supports those characters (e.g. see FAQ in https://www.reportbro.com/support/index )

PS: such questions are better asked in the mailing list since this is probably not a reportbro issue.

**Comment by alhman** [comment]
Since there was no more feedback I assume you could resolve the issue. Otherwise post in the mailing list or write us an email.
