### ISSUE TITLE
Image Paramater Type

### ISSUE THREAD

**Issue by lachlanhickey** [jobsta/reportbro-designer#44]
I'm really stuck on trying to implement a parameter type: image and using a base64_encoded image as test data. 

What fields should I be using for an image type? It this documented somewhere that I'm missing?

**Comment by mariarauch** [comment]
@lachlanhickey The image type is documented here (search for base64):
https://www.reportbro.com/docs/methods

If the image is base64 then you need to pass a string with this prefix
"data:image/<image type>;base64," followed by the base64-data itself.

Alternatively you can also pass an I/O object or a file path of the
image file (png or jpeg).

**Comment by lachlanhickey** [comment]
But how do I represent this as a parameter? Do I define the testData parameter?
Like this?
`'id' => 1,
					'name' => 'Image',
					'type' => 'image',
					'arrayItemType' => 'string',
					'eval' => false,
					'nullable' => false,
					'pattern' => '',
					'expression' => '',
					'showOnlyNameType' => false,
					'testData' => 'data:image/;base64'
`

**Comment by mariarauch** [comment]
The parameter is defined in ReportBro Designer and also includes the
test data which is used when you preview the Report in the Designer.

If you want to use your real application data instead of the parameter
test data then you have to define your own parameters (a dict which is
passed to the Report instance) and set the values accordingly. An
example can be seen in the demo app:
https://github.com/jobsta/albumapp-django/blob/a42588073959f7890b40385b9a9df46069706469/albums/album_views.py#L76

as you can see these parameters match the parameters from the Designer
template. e.g. the parameter current_date is defined as Date type,
therefor we pass a datetime.datetime instance with the same name. If
you'd add an image parameter 'img' in the report template then you'd
have to add something like this to your server code for a png-image:

params['img'] = 'data:image/png;base64,<img64>'

where <img64> must be replaced with the base64-encoded image data

**Comment by lachlanhickey** [comment]
I'm not sure if you understand my issue/question correctly. 

Question 1: Do I use the field 'testData' to pass a data URI? If no, how do I pass a data URI in the designer?
Question 2: How do I assign a parameter image to an actual image. Do insert the parameter name into the source?

When previewing a designed report, with an image parameter parsed as base64 encoded data URL, I am getting a blank image.

**Comment by lachlanhickey** [comment]
Ok, I've figured it out. 

Frontend, passing a data URL functions. 

Designer/Preview: testData => 'data:image/png;base64,`img64`' prints a blank image. Any thoughts?

**Comment by mariarauch** [comment]
I assume there is some confusion. If you use an image parameter in the
Designer there is no preview possible.

Steps to create an image in Designer:
1. add parameter
2. set name, e.g. "img" and set type to "image"
3. drag image element onto layout
4. Set img parameter as source for image element, so Source will be "${img}"

When you click the Play (Preview) button in the Designer, the image will
always be empty. That's because no test data is possible for an image
parameter and when you run a preview only the test data (stored within
the parameters) will be used as report data. The report definition is
still correct.

Now you need a new endpoint in your app so you can use this report
definition together with your real application data (see report function
in album_views.py in the demo app). There you can set your image (either
I/O object or base64 encoded) for the "img" parameter as mentioned in
my previous comment.

**Comment by lachlanhickey** [comment]
Ok, so conclusion, you cannot preview, or set 'testData' with the type set to "image".
 
This is odd, as I can preview images based on URL's, or uploaded images sources. 

Can this be moved to a feature request, please.

**Comment by alhman** [comment]
It is now possible to set test data for image parameters in v3, as well as for image parameters inside lists or collections.
