### ISSUE TITLE
Report design - horizontal line

### ISSUE THREAD

**Issue by yao-big** [jobsta/reportbro-designer#67]
When the width is 1 and the height is 100, the designer displays normally and the preview is abnormal

report-design:
![image](https://user-images.githubusercontent.com/30170943/131960158-9fc83ad3-f6b3-40a2-b370-07ed110cf9b4.png)
preview
![image](https://user-images.githubusercontent.com/30170943/131960190-d3ff8ea3-867c-4175-b4cd-b27d70bff9ca.png)

**Comment by yao-big** [comment]
@alhman

**Comment by alhman** [comment]
When rendering the pdf we set the line width (which is the line height in the designer). The problem is that this line width is more like a brush width, i.e. the the width is applied horizontally and vertically.

We have to fix pdf rendering for thick lines. This also means that the line width must be larger than the height.

In your case you probably need a vertical line (which we currently don't support). You could also make a workaround with a text field with either a background color or with a left border.

**Comment by yao-big** [comment]
ok
