### ISSUE TITLE
Barcode bursts frame.

### ISSUE THREAD

**Issue by GlauberF** [jobsta/reportbro-designer#80]
When using frame to group the elements, the barcode overflows the frame limits, not respecting.
In the example below I tested with a random data, but here I test locally with a code with 13 digits and it still pops.

![Captura de Tela_selecionar área_20220704102133](https://user-images.githubusercontent.com/11314585/177162828-5201b6e3-3d41-4082-9bf6-59e11d7f2065.png)

![Captura de Tela_selecionar área_20220704102146](https://user-images.githubusercontent.com/11314585/177162845-bd14458c-393b-41ce-9c66-c68b083b2b94.png)

**Comment by alhman** [comment]
what is the expected behavior? I only see the following options

- abort report generation with error
- crop bar code at frame end (would result in invalid barcode)
- scale bar code so it fits into the frame width (would probably also result in invalid / unreadable bar code because it is too small)
- generate full bar code and allow overflow (current behavior)

unlike a text the bar code cannot be wrapped into multiple lines. I only see the first and last option als viable options. The first option would be technically correct but I don't know if this is actually any better because then a report can easily fail depending on given parameter input.

**Comment by GlauberF** [comment]
I don't know how it goes down in the library. But I understand that the barcode could be transformed into an image and then resize the image without losing its characteristics or deforming it.

**Comment by alhman** [comment]
Of course it could be scaled (option three I mentioned above) but this would result in unreadable bar codes. A bar code is not useful if it cannot be scanned. That's why you only define the height and the width depends on the generated bar code.

The only other option is to abort with an error but I doubt this makes it any better. When you generate a report you have to make sure that
a) the bar code area is large enough in the report template
b) the bar code value contains valid data

**Comment by GlauberF** [comment]
I think my problem is with the barcode type, I would need ean13.
is there any way to generate instead of code128 ?

**Comment by alhman** [comment]
currently not but once we drop support for Python 2 we should be able include other bar code formats.

**Comment by GlauberF** [comment]
@alhman waiting anxiously.

**Comment by GlauberF** [comment]
@alhman I would urgently need to be able to use EAN13, can I implement something?
Because I understand that we could use font.
https://www.netfontes.com.br/view/ean13/

But I would like something through the barcode component.

**Comment by GlauberF** [comment]
To get around the problem of not having EAN13, I generated a base64 image and it worked.
I believe that this could be done with the barcode and it would still be valid, as I have tested it in practice.

**Comment by alhman** [comment]
Additional barcodes such as EAN13 are now available in v3.2.0
